jwt:
  secret: aVeryLongSecretKeyThatNeedsToBeAtLeast32BytesLongToWorkWithJjwt
  expiration: 7200000

spring:
  application:
    name: da-hub-api

  datasource:
    url: jdbc:h2:mem:dahub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    com.dahub: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
